/**
 * Généré par scripts/import-gallery-images.mjs — ne pas modifier à la main.
 * Relancer: npm run import:gallery
 */
import type { Artwork } from './types';

export const GALLERY_ARTWORKS: Artwork[] = [
  {
    "id": "gallery-sculptors-01",
    "title": "Sculpture 01",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-01-2489996626.jpg",
    "descriptionFr": "Pièce 01 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 01 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-02",
    "title": "Sculpture 02",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-02-2489996627.jpg",
    "descriptionFr": "Pièce 02 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 02 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-03",
    "title": "Sculpture 03",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-03-2489996628.jpg",
    "descriptionFr": "Pièce 03 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 03 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-04",
    "title": "Sculpture 04",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-04-2489996629.jpg",
    "descriptionFr": "Pièce 04 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 04 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-05",
    "title": "Sculpture 05",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-05-2489996630.jpg",
    "descriptionFr": "Pièce 05 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 05 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-06",
    "title": "Sculpture 06",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-06-2489996631.jpg",
    "descriptionFr": "Pièce 06 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 06 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-07",
    "title": "Sculpture 07",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-07-2489996632.jpg",
    "descriptionFr": "Pièce 07 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 07 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-08",
    "title": "Sculpture 08",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-08-2489996633.png",
    "descriptionFr": "Pièce 08 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 08 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-09",
    "title": "Sculpture 09",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-09-2489996634.jpg",
    "descriptionFr": "Pièce 09 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 09 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-10",
    "title": "Sculpture 10",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-10-2489996635.jpg",
    "descriptionFr": "Pièce 10 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 10 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-11",
    "title": "Sculpture 11",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-11-2489996636.png",
    "descriptionFr": "Pièce 11 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 11 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-12",
    "title": "Sculpture 12",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-12-2489996637.jpg",
    "descriptionFr": "Pièce 12 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 12 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-13",
    "title": "Sculpture 13",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-13-2489996638.png",
    "descriptionFr": "Pièce 13 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 13 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-14",
    "title": "Sculpture 14",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-14-2489996639.png",
    "descriptionFr": "Pièce 14 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 14 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-15",
    "title": "Sculpture 15",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-15-2489996640.png",
    "descriptionFr": "Pièce 15 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 15 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-16",
    "title": "Sculpture 16",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-16-2489996641.png",
    "descriptionFr": "Pièce 16 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 16 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-17",
    "title": "Sculpture 17",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-17-2489996642.jpg",
    "descriptionFr": "Pièce 17 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 17 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-18",
    "title": "Sculpture 18",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-18-2489996643.png",
    "descriptionFr": "Pièce 18 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 18 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-19",
    "title": "Sculpture 19",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-19-2489996644.png",
    "descriptionFr": "Pièce 19 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 19 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-20",
    "title": "Sculpture 20",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-20-2489996645.png",
    "descriptionFr": "Pièce 20 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 20 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-21",
    "title": "Sculpture 21",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-21-2489996646.png",
    "descriptionFr": "Pièce 21 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 21 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-22",
    "title": "Sculpture 22",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-22-2426529821.jpg",
    "descriptionFr": "Pièce 22 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 22 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-23",
    "title": "Sculpture 23",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-23-2426529822.jpg",
    "descriptionFr": "Pièce 23 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 23 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-24",
    "title": "Sculpture 24",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-24-2426529823.jpg",
    "descriptionFr": "Pièce 24 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 24 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-25",
    "title": "Sculpture 25",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-25-2426529824.jpg",
    "descriptionFr": "Pièce 25 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 25 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-26",
    "title": "Sculpture 26",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-26-2426529825.jpg",
    "descriptionFr": "Pièce 26 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 26 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-27",
    "title": "Sculpture 27",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-27-2426529826.jpg",
    "descriptionFr": "Pièce 27 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 27 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-28",
    "title": "Sculpture 28",
    "artistId": "serge-couvert",
    "artistName": "Serge COUVERT",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-28-2426529827.jpg",
    "descriptionFr": "Pièce 28 de la collection permanente de Serge COUVERT, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 28 from Serge COUVERT's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-sculptors-29",
    "title": "Sculpture 29",
    "artistId": "dominique-rayou",
    "artistName": "Dominique RAYOU",
    "category": "SCULPTORS",
    "medium": "Bronze, marbre ou bois sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Sculpture",
    "image": "/images/gallery/sculptors/sculptors-29-2426529828.jpg",
    "descriptionFr": "Pièce 29 de la collection permanente de Dominique RAYOU, exposée à la galerie CLASS 41 Paris.",
    "descriptionEn": "Piece 29 from Dominique RAYOU's permanent collection, on view at Galerie CLASS 41 Paris.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-01",
    "title": "Verre soufflé 01",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-01-2434474031.jpg",
    "descriptionFr": "Œuvre en verre 01 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 01 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-02",
    "title": "Verre soufflé 02",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-02-2434474032.jpg",
    "descriptionFr": "Œuvre en verre 02 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 02 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-03",
    "title": "Verre soufflé 03",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-03-2434474033.jpg",
    "descriptionFr": "Œuvre en verre 03 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 03 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-04",
    "title": "Verre soufflé 04",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-04-2434474034.jpg",
    "descriptionFr": "Œuvre en verre 04 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 04 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-05",
    "title": "Verre soufflé 05",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-05-2434474035.jpg",
    "descriptionFr": "Œuvre en verre 05 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 05 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-06",
    "title": "Verre soufflé 06",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-06-2434474036.jpg",
    "descriptionFr": "Œuvre en verre 06 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 06 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-07",
    "title": "Verre soufflé 07",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-07-2434474037.jpg",
    "descriptionFr": "Œuvre en verre 07 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 07 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-08",
    "title": "Verre soufflé 08",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-08-2434474038.jpg",
    "descriptionFr": "Œuvre en verre 08 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 08 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-09",
    "title": "Verre soufflé 09",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-09-2434474039.jpg",
    "descriptionFr": "Œuvre en verre 09 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 09 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-10",
    "title": "Verre soufflé 10",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-10-2418360587.jpg",
    "descriptionFr": "Œuvre en verre 10 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 10 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-11",
    "title": "Verre soufflé 11",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-11-2418360588.jpg",
    "descriptionFr": "Œuvre en verre 11 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 11 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-12",
    "title": "Verre soufflé 12",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-12-2418360589.jpg",
    "descriptionFr": "Œuvre en verre 12 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 12 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-13",
    "title": "Verre soufflé 13",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-13-2418360590.jpg",
    "descriptionFr": "Œuvre en verre 13 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 13 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-14",
    "title": "Verre soufflé 14",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-14-2418360591.jpg",
    "descriptionFr": "Œuvre en verre 14 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 14 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-15",
    "title": "Verre soufflé 15",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-15-2418360592.jpg",
    "descriptionFr": "Œuvre en verre 15 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 15 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-16",
    "title": "Verre soufflé 16",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-16-2417341444.jpg",
    "descriptionFr": "Œuvre en verre 16 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 16 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-17",
    "title": "Verre soufflé 17",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-17-2417341445.jpg",
    "descriptionFr": "Œuvre en verre 17 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 17 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-18",
    "title": "Verre soufflé 18",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-18-2417341446.jpg",
    "descriptionFr": "Œuvre en verre 18 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 18 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-19",
    "title": "Verre soufflé 19",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-19-2417341447.jpg",
    "descriptionFr": "Œuvre en verre 19 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 19 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-20",
    "title": "Verre soufflé 20",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-20-2417341448.jpg",
    "descriptionFr": "Œuvre en verre 20 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 20 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-glass-21",
    "title": "Verre soufflé 21",
    "artistId": "jean-pierre-umberto",
    "artistName": "Jean-Pierre UMBERTO",
    "category": "GLASS",
    "medium": "Verre soufflé et sculpté",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Verre d'art",
    "image": "/images/gallery/glass/glass-21-2417341449.jpg",
    "descriptionFr": "Œuvre en verre 21 de Jean-Pierre UMBERTO — prismes, bulles et lumière capturés dans la matière.",
    "descriptionEn": "Glass work 21 by Jean-Pierre UMBERTO — light, bubbles and form captured in silica.",
    "isOnlineOnly": false,
    "onExhibit": true
  },
  {
    "id": "gallery-painters-01",
    "title": "Toile 01",
    "artistId": "irini",
    "artistName": "IRINI",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-01-2489176449.jpg",
    "descriptionFr": "Tableau 01 de IRINI, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 01 by IRINI, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": true,
    "onExhibit": false,
    "price": "Sur demande"
  },
  {
    "id": "gallery-painters-02",
    "title": "Toile 02",
    "artistId": "arthur-gaida",
    "artistName": "Arthur GAÏDA",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-02-2489176450.jpg",
    "descriptionFr": "Tableau 02 de Arthur GAÏDA, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 02 by Arthur GAÏDA, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": false,
    "onExhibit": false
  },
  {
    "id": "gallery-painters-03",
    "title": "Toile 03",
    "artistId": "irini",
    "artistName": "IRINI",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-03-2489176451.jpg",
    "descriptionFr": "Tableau 03 de IRINI, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 03 by IRINI, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": true,
    "onExhibit": false,
    "price": "Sur demande"
  },
  {
    "id": "gallery-painters-04",
    "title": "Toile 04",
    "artistId": "arthur-gaida",
    "artistName": "Arthur GAÏDA",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-04-2489176452.jpg",
    "descriptionFr": "Tableau 04 de Arthur GAÏDA, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 04 by Arthur GAÏDA, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": false,
    "onExhibit": false
  },
  {
    "id": "gallery-painters-05",
    "title": "Toile 05",
    "artistId": "irini",
    "artistName": "IRINI",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-05-2489176453.jpg",
    "descriptionFr": "Tableau 05 de IRINI, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 05 by IRINI, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": true,
    "onExhibit": false,
    "price": "Sur demande"
  },
  {
    "id": "gallery-painters-06",
    "title": "Toile 06",
    "artistId": "arthur-gaida",
    "artistName": "Arthur GAÏDA",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-06-2489176454.jpg",
    "descriptionFr": "Tableau 06 de Arthur GAÏDA, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 06 by Arthur GAÏDA, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": false,
    "onExhibit": false
  },
  {
    "id": "gallery-painters-07",
    "title": "Toile 07",
    "artistId": "irini",
    "artistName": "IRINI",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-07-2489176455.jpg",
    "descriptionFr": "Tableau 07 de IRINI, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 07 by IRINI, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": true,
    "onExhibit": false,
    "price": "Sur demande"
  },
  {
    "id": "gallery-painters-08",
    "title": "Toile 08",
    "artistId": "arthur-gaida",
    "artistName": "Arthur GAÏDA",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-08-2489176456.jpg",
    "descriptionFr": "Tableau 08 de Arthur GAÏDA, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 08 by Arthur GAÏDA, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": false,
    "onExhibit": false
  },
  {
    "id": "gallery-painters-09",
    "title": "Toile 09",
    "artistId": "irini",
    "artistName": "IRINI",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-09-2489176457.jpg",
    "descriptionFr": "Tableau 09 de IRINI, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 09 by IRINI, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": true,
    "onExhibit": false,
    "price": "Sur demande"
  },
  {
    "id": "gallery-painters-10",
    "title": "Toile 10",
    "artistId": "arthur-gaida",
    "artistName": "Arthur GAÏDA",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-10-2489176458.jpg",
    "descriptionFr": "Tableau 10 de Arthur GAÏDA, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 10 by Arthur GAÏDA, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": false,
    "onExhibit": false
  },
  {
    "id": "gallery-painters-11",
    "title": "Toile 11",
    "artistId": "irini",
    "artistName": "IRINI",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-11-2489176459.jpg",
    "descriptionFr": "Tableau 11 de IRINI, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 11 by IRINI, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": true,
    "onExhibit": false,
    "price": "Sur demande"
  },
  {
    "id": "gallery-painters-12",
    "title": "Toile 12",
    "artistId": "arthur-gaida",
    "artistName": "Arthur GAÏDA",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-12-2489176460.jpg",
    "descriptionFr": "Tableau 12 de Arthur GAÏDA, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 12 by Arthur GAÏDA, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": false,
    "onExhibit": false
  },
  {
    "id": "gallery-painters-13",
    "title": "Toile 13",
    "artistId": "irini",
    "artistName": "IRINI",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-13-2489176461.jpg",
    "descriptionFr": "Tableau 13 de IRINI, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 13 by IRINI, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": true,
    "onExhibit": false,
    "price": "Sur demande"
  },
  {
    "id": "gallery-painters-14",
    "title": "Toile 14",
    "artistId": "arthur-gaida",
    "artistName": "Arthur GAÏDA",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-14-2489176462.jpg",
    "descriptionFr": "Tableau 14 de Arthur GAÏDA, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 14 by Arthur GAÏDA, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": false,
    "onExhibit": false
  },
  {
    "id": "gallery-painters-15",
    "title": "Toile 15",
    "artistId": "irini",
    "artistName": "IRINI",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-15-2489176463.jpg",
    "descriptionFr": "Tableau 15 de IRINI, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 15 by IRINI, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": true,
    "onExhibit": false,
    "price": "Sur demande"
  },
  {
    "id": "gallery-painters-16",
    "title": "Toile 16",
    "artistId": "arthur-gaida",
    "artistName": "Arthur GAÏDA",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-16-2489176464.jpg",
    "descriptionFr": "Tableau 16 de Arthur GAÏDA, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 16 by Arthur GAÏDA, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": false,
    "onExhibit": false
  },
  {
    "id": "gallery-painters-17",
    "title": "Toile 17",
    "artistId": "irini",
    "artistName": "IRINI",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-17-2489176407.jpg",
    "descriptionFr": "Tableau 17 de IRINI, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 17 by IRINI, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": true,
    "onExhibit": false,
    "price": "Sur demande"
  },
  {
    "id": "gallery-painters-18",
    "title": "Toile 18",
    "artistId": "arthur-gaida",
    "artistName": "Arthur GAÏDA",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-18-2489176408.jpg",
    "descriptionFr": "Tableau 18 de Arthur GAÏDA, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 18 by Arthur GAÏDA, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": false,
    "onExhibit": false
  },
  {
    "id": "gallery-painters-19",
    "title": "Toile 19",
    "artistId": "irini",
    "artistName": "IRINI",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-19-2489176409.jpg",
    "descriptionFr": "Tableau 19 de IRINI, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 19 by IRINI, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": true,
    "onExhibit": false,
    "price": "Sur demande"
  },
  {
    "id": "gallery-painters-20",
    "title": "Toile 20",
    "artistId": "arthur-gaida",
    "artistName": "Arthur GAÏDA",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-20-2489176410.jpg",
    "descriptionFr": "Tableau 20 de Arthur GAÏDA, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 20 by Arthur GAÏDA, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": false,
    "onExhibit": false
  },
  {
    "id": "gallery-painters-21",
    "title": "Toile 21",
    "artistId": "irini",
    "artistName": "IRINI",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-21-2489176411.jpg",
    "descriptionFr": "Tableau 21 de IRINI, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 21 by IRINI, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": true,
    "onExhibit": false,
    "price": "Sur demande"
  },
  {
    "id": "gallery-painters-22",
    "title": "Toile 22",
    "artistId": "arthur-gaida",
    "artistName": "Arthur GAÏDA",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-22-2489176412.jpg",
    "descriptionFr": "Tableau 22 de Arthur GAÏDA, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 22 by Arthur GAÏDA, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": false,
    "onExhibit": false
  },
  {
    "id": "gallery-painters-23",
    "title": "Toile 23",
    "artistId": "irini",
    "artistName": "IRINI",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-23-2489176413.jpg",
    "descriptionFr": "Tableau 23 de IRINI, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 23 by IRINI, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": true,
    "onExhibit": false,
    "price": "Sur demande"
  },
  {
    "id": "gallery-painters-24",
    "title": "Toile 24",
    "artistId": "arthur-gaida",
    "artistName": "Arthur GAÏDA",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-24-2489176414.jpg",
    "descriptionFr": "Tableau 24 de Arthur GAÏDA, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 24 by Arthur GAÏDA, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": false,
    "onExhibit": false
  },
  {
    "id": "gallery-painters-25",
    "title": "Toile 25",
    "artistId": "irini",
    "artistName": "IRINI",
    "category": "PAINTERS",
    "medium": "Huile ou technique mixte sur toile",
    "year": "—",
    "dimensions": "Sur demande",
    "material": "Peinture",
    "image": "/images/gallery/painters/painters-25-2489176415.jpg",
    "descriptionFr": "Tableau 25 de IRINI, issu du catalogue de la Galerie CLASS 41.",
    "descriptionEn": "Painting 25 by IRINI, from the Galerie CLASS 41 catalog.",
    "isOnlineOnly": true,
    "onExhibit": false,
    "price": "Sur demande"
  }
];

export const GALLERY_ARTWORK_COUNT = 75;
